# Databricks notebook source
# MAGIC %md
# MAGIC INITIAL IDEA OF COMBINING DATA

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT
# MAGIC   IMGW.VOIVODESHIP,
# MAGIC   IMGW.LATEST_MEASUREMENT_TIMESTAMP,
# MAGIC   IMGW.AVG_TEMP_WOJ,
# MAGIC   IMGW.AVG_WIND_SPD_WOJ,
# MAGIC   IMGW.AVG_HUMIDITY_WOJ,
# MAGIC   IMGW.AVG_RAIN_WOJ,
# MAGIC   IMGW.AVG_PRESSURE_WOJ,
# MAGIC   IMGW.LATEST_MEASUREMENT_WATER_TIMESTAMP,
# MAGIC   IMGW.AVG_WATER_WOJ,
# MAGIC   IMGW.AVG_WATER_TEMP_WOJ,
# MAGIC   IMGW.LATEST_MEASUREMENT_ICE_TIMESTAMP,
# MAGIC   IMGW.MAX_ICE_OCCR_WOJ,
# MAGIC   IMGW.LATEST_MEASUREMENT_ENCHROACHING_TIMESTAMP,
# MAGIC   IMGW.MAX_ENCHROACHING_WOJ,
# MAGIC   GIOS.AIR_QUALITY_CHECK_TS,
# MAGIC   GIOS.AVG_RANK AS AVG_AIR_QUALITY_RANK,
# MAGIC   GIOS.MARK AS AIR_QUALITY_MARK
# MAGIC FROM silver.imgw_data IMGW
# MAGIC LEFT JOIN silver.gios_data GIOS
# MAGIC ON IMGW.VOIVODESHIP = GIOS.VOIVODESHIP
